name: yundera
services:
  admin:
    image: ghcr.io/yundera/settings-center-app:1.1.25
    container_name: admin
    hostname: admin
    restart: unless-stopped
    environment:
      AUTHORITY_ENDPOINT: "https://8080-casaos-%DOMAIN%/v1/users"
      COMPOSE_FOLDER_PATH: "/DATA/AppData/casaos/apps/yundera/"
    volumes:
      # This gives the admin app ssh root access (used to update the system)
      - type: bind
        source: /root/.ssh/
        target: /host_ssh/
      # This gives the admin app access to its own data (used to update itself)
      - type: bind
        source: /DATA/AppData/casaos/apps/yundera/
        target: /app/data
    expose:
      - "80"
    networks:
      pcs: null

  casaos:
    image: ghcr.io/yundera/casa-img:0.4.15-42
    container_name: casaos
    hostname: casaos
    restart: unless-stopped
    environment:
      PUID: 1000 # user ID used by casaos to read and write files
      PGID: 1000 # group ID used by casaos to read and write files
      USER: "%DEFAULT_USER%" # casaos default initial user (optional)
      DATA_ROOT: "/DATA" # where casaos apps data are stored

      # Environment variables used by casaos to configure reverse proxy in the app settings (not used by casaos system)
      REF_DOMAIN: "%DOMAIN%"
      REF_NET: "pcs"
      REF_PORT: "443"
      REF_SCHEME: "https"

      # V1 these envs are not used directly by casaos but are forwarded to the app at creation, injected in the docker compose up
      default_pwd: "%DEFAULT_PWD%"
      public_ip: "%PUBLIC_IPV4%"
      domain: "%DOMAIN%"

      # V2 these envs are not used directly by casaos but are forwarded to the app at creation, injected in the docker compose up
      PCS_DEFAULT_PASSWORD: "%DEFAULT_PWD%"
      PCS_DOMAIN: "%DOMAIN%" # without https://
      PCS_DATA_ROOT: "/DATA"
      PCS_PUBLIC_IP: "%PUBLIC_IPV4%"
      PCS_PUBLIC_IPV6: "%PUBLIC_IPV6%"
      PCS_EMAIL: "admin@%DOMAIN%"

      # SMTP configuration for magic link and password reset emails
      SMTP_HOST: "smtp"
      SMTP_PORT: "587"

    networks:
      pcs: null
    volumes:
      - type: bind
        source: /DATA
        target: /DATA
        # Add bind propagation for FUSE mounts
        bind:
          propagation: rshared
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /dev
        target: /dev

  mesh-router:
    # Use temporary verion of mesh router the repo is being refactored and the image name is broken for now - will be fix in new version
    image: pierreh37/mesh-router:1.0.12
    # image: ghcr.io/yundera/mesh-router:1.0.12
    container_name: mesh-router
    hostname: mesh-router
    restart: unless-stopped
    environment:
      - PROVIDER=%PROVIDER_STR%
    networks:
      pcs: null
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.conf.all.src_valid_mark: "1"
      net.ipv4.ip_forward: "1"

  smtp:
    image: ghcr.io/yundera/yundera-smtp-handler:1.0.1
    container_name: smtp
    hostname: smtp
    restart: unless-stopped
    environment:
      USER_JWT: "%USER_JWT%"
      ORCHESTRATOR_URL: "%YUNDERA_USER_API%"
      SMTP_PORT: "587"
    expose:
      - "587"
    networks:
      pcs: null

networks:
  pcs:
    name: pcs

x-casaos:
  main: admin
  author: Yundera Team
  category: pcs
  hostname: admin-%DOMAIN%
  icon: https://cdn.jsdelivr.net/gh/Yundera/settings-center-app@main/public/YunderaPCS-setting_iconV2.svg
  index: /
  is_uncontrolled: false
  port_map: ""
  scheme: https
  store_app_id: yundera
  title:
    custom: Settings
