#!/bin/bash
# ensure-casadash-stack.sh - Deploy CasaDash behind its AppShield gate.
#
# CasaDash (github.com/worph/CasaDash) is the dashboard-only CasaOS replacement.
# Phase 1 runs it ALONGSIDE CasaOS: it lists and can manage every app, while CasaOS
# stays the only installer. See doc/casadash-migration.md.
#
# Deployed to /DATA/AppData/casadash. The name carries no leading dot, so CasaDash's
# own managed-app scan of /DATA/AppData (it skips any name containing a dot) picks the
# stack up and the dashboard tiles itself. That is deliberate: it is not hidden.
#
# SECURITY: CasaDash ships with no authentication whatsoever and mounts the Docker
# socket. The compose file never publishes its port — the AppShield gate in the same
# stack is the only way in. Do not "temporarily" add a ports: mapping to debug.
#
# ORDERING: must run AFTER ensure-user-compose-stack-up.sh — the `pcs` network is
# owned by the yundera stack and joined here as external, and the gate depends on
# auth-registrar / dex (yundera stack) and casaos-oidc-bridge (casaos stack) being
# reachable by name on that network.
set -euo pipefail

YND_ROOT="/DATA/AppData/casaos/apps/yundera"
source "$YND_ROOT/scripts/library/log.sh"

# The casadash container talks to the Docker socket as a non-root user, so it needs
# the socket's group. Resolve it from the host rather than assuming the usual 999.
if [ ! -S /var/run/docker.sock ]; then
    log_error "/var/run/docker.sock not found; cannot determine DOCKER_GID"
    exit 1
fi
DOCKER_GID="$(stat -c '%g' /var/run/docker.sock)"

# CasaDash stamps container timezones from TZ. The unified .env does not carry it.
if [ -f /etc/timezone ]; then
    TZ="$(cat /etc/timezone 2>/dev/null || echo UTC)"
elif [ -L /etc/localtime ]; then
    TZ="$(readlink /etc/localtime | sed 's|.*/zoneinfo/||')"
else
    TZ="UTC"
fi

# --- legacy location ----------------------------------------------------------
# The stack used to be deployed to the hidden /DATA/AppData/.casadash, which never left
# staging. Everything CasaDash now lives in the dotless /DATA/AppData/casadash — the
# stack AND CasaDash's own state (settings, store cache, .env.app) — so the old path is
# dead. Drop it.
rm -rf /DATA/AppData/.casadash

# --- .env.app: what every app CasaDash installs receives -----------------------
# The deployment's statement of the world it places apps into: the network they join,
# the domain and public IP their Caddy routes are templated with, the identity they seed
# an admin account from. CasaDash forwards each key below into every app's own .env, on
# install and again on every start — so a box that changes domain or IP carries its apps
# with it, instead of stranding them on the deployment they were installed against.
# See CasaDash's docs/app-env.md.
#
# It goes in the stack's own directory, which is also CasaDash's state directory
# (DATA_ROOT/AppData/casadash). Written BEFORE deploy-stack.sh, so a first-ever install
# finds it already there and never falls back to CasaDash's built-in default — that
# default is a standalone local install (`APP_NET=mesh`, no domain), and `mesh` does not
# exist on a PCS, so every app would fail to start.
#
# Rewritten on every self-check from the unified .env, the single source of environment
# truth.
APPENV_DIR="/DATA/AppData/casadash"
UNIFIED_ENV="$YND_ROOT/.env"

env_get() {
    "$YND_ROOT/scripts/tools/env-file-manager.sh" get "$1" "$UNIFIED_ENV" 2>/dev/null || true
}

mkdir -p "$APPENV_DIR"

# Written to a temp file and moved into place: CasaDash reads .env.app from another
# container, at any moment, to start an app — it must never observe a half-written one.
APPENV_TMP="$(mktemp "$APPENV_DIR/.env.app.XXXXXX")"
cat > "$APPENV_TMP" <<EOF
# Generated by ensure-casadash-stack.sh from the yundera unified .env.
# DO NOT EDIT — rewritten on every self-check. Change .pcs.env / .ynd.user.env instead.
#
# The variables CasaDash forwards into every app it manages; see docs/app-env.md.
APP_NET=pcs
APP_DATA_ROOT=/DATA
APP_DOMAIN=$(env_get DOMAIN)
domain=$(env_get DOMAIN)
APP_PUBLIC_IP=$(env_get PUBLIC_IP)
APP_PUBLIC_IP_DASH=$(env_get PUBLIC_IP_DASH)
APP_PUBLIC_IPV4=$(env_get PUBLIC_IPV4)
APP_PUBLIC_IPV4_DASH=$(env_get PUBLIC_IPV4_DASH)
APP_PUBLIC_IPV6=$(env_get PUBLIC_IPV6)
APP_PUBLIC_IPV6_DASH=$(env_get PUBLIC_IPV6_DASH)
APP_EMAIL=$(env_get EMAIL)
APP_DEFAULT_PASSWORD=$(env_get DEFAULT_PWD)
DefaultUserName=admin
DefaultPassword=$(env_get DEFAULT_PWD)
EOF

# Carries DEFAULT_PWD, exactly as the unified .env does. CasaDash runs as root and is
# the only reader.
chmod 600 "$APPENV_TMP"
mv -f "$APPENV_TMP" "$APPENV_DIR/.env.app"
log_info "Wrote $APPENV_DIR/.env.app"

exec "$YND_ROOT/scripts/tools/deploy-stack.sh" casadash /DATA/AppData/casadash \
    "DOCKER_GID=$DOCKER_GID" \
    "TZ=$TZ"
