#!/bin/bash
# Validate required environment variables and generate combined .env file

set -e

YND_ROOT="/DATA/AppData/casaos/apps/yundera"
PCS_ENV_FILE="$YND_ROOT/.pcs.env"
SECRET_ENV_FILE="$YND_ROOT/.pcs.secret.env"
USER_ENV_FILE="$YND_ROOT/.ynd.user.env"
OUTPUT_ENV_FILE="$YND_ROOT/.env"

# Sanitize all env files before processing using unified env file manager
"$YND_ROOT/scripts/tools/env-file-manager.sh" sanitize "$PCS_ENV_FILE"
"$YND_ROOT/scripts/tools/env-file-manager.sh" sanitize "$SECRET_ENV_FILE"
"$YND_ROOT/scripts/tools/env-file-manager.sh" sanitize "$USER_ENV_FILE"

# Define required environment variables
REQUIRED_VARS=("DOMAIN" "PROVIDER_STR" "UID")

# Declare associative array to store environment variables
declare -A env_vars

# Function to read environment file and store variables
read_env_file() {
    local file="$1"
    if [ -f "$file" ]; then
        while IFS='=' read -r key value || [ -n "$key" ]; do
            # Skip comments and empty lines
            [[ $key =~ ^#.*$ || -z $key ]] && continue

            # Remove any surrounding quotes from the value
            value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")

            # Store the key-value pair
            env_vars["$key"]="$value"

        done < "$file"
    else
        echo "Warning: Environment file not found: $file" >&2
    fi
}

# Read all three environment files
read_env_file "$PCS_ENV_FILE"
read_env_file "$SECRET_ENV_FILE"
read_env_file "$USER_ENV_FILE"

# Set default values for optional variables if not already set
ENV_MANAGER="$YND_ROOT/scripts/tools/env-file-manager.sh"

# DEFAULT_SERVICE_HOST / _PORT: what the root domain (${DOMAIN} and the two IP
# fallbacks, routed in the Caddyfile) resolves to. `maison` is the AppShield gate
# in the maison stack, which exposes 80 and fronts the dashboard — NOT `maison-app`,
# which has no auth of its own. Was casaos:8080 until CasaOS was removed; existing
# hosts are repointed by migrations/2026-08-02-14-remove-casaos-stack.sh.
if ! "$ENV_MANAGER" exists DEFAULT_SERVICE_HOST "$PCS_ENV_FILE"; then
    "$ENV_MANAGER" set DEFAULT_SERVICE_HOST "maison" "$PCS_ENV_FILE"
    echo "Set default DEFAULT_SERVICE_HOST=maison"
fi

if ! "$ENV_MANAGER" exists DEFAULT_SERVICE_PORT "$PCS_ENV_FILE"; then
    "$ENV_MANAGER" set DEFAULT_SERVICE_PORT "80" "$PCS_ENV_FILE"
    echo "Set default DEFAULT_SERVICE_PORT=80"
fi

# NOTE: no JWT_SECRET here any more. It used to be minted for the
# settings-center-app's OIDC state cookie, but that cookie — and the admin
# session cookie — are now signed with a key the app persists itself at
# /app/data/admin-session-key (src/backend/auth/sessionKey.ts), precisely so a
# container restart does not sign everyone out. Nothing reads JWT_SECRET.
# Existing hosts are cleaned by migrations/2026-08-02-12-drop-admin-jwt-secret.sh.

# Re-read env files to include any newly set defaults
read_env_file "$PCS_ENV_FILE"
read_env_file "$SECRET_ENV_FILE"

# Check if all required variables are set and not empty
missing_vars=()
for var in "${REQUIRED_VARS[@]}"; do
    if [[ -z "${env_vars[$var]}" ]]; then
        missing_vars+=("$var")
    fi
done

# Throw error if any required variables are missing
if [[ ${#missing_vars[@]} -gt 0 ]]; then
    echo "Error: The following required environment variables are not set or are empty:" >&2
    printf "  - %s\n" "${missing_vars[@]}" >&2
    echo "Please set these variables in $PCS_ENV_FILE, $SECRET_ENV_FILE, or $USER_ENV_FILE" >&2
    exit 1
fi

# Generate combined .env file for Docker Compose.
#
# Perms first, content second: this file concatenates .pcs.secret.env verbatim
# (USER_JWT, DEFAULT_PWD, PROVIDER_STR, AUTHELIA_DEX_SECRET), so it is exactly as
# sensitive as its 600 sources — and `>` preserves the mode of an already-existing
# file, which is how it ended up world-readable on hosts provisioned before this.
# Every derived copy is already 600 (see tools/deploy-stack.sh); this is the
# original. Created empty at 600, then filled.
: > "$OUTPUT_ENV_FILE"
chmod 600 "$OUTPUT_ENV_FILE"

{
    echo "# AUTO-GENERATED FILE - DO NOT EDIT"
    echo "# This file is automatically generated from:"
    echo "#   - .pcs.env"
    echo "#   - .pcs.secret.env"
    echo "#   - .ynd.user.env"
    echo "# Any changes will be overwritten on next system update."
    echo "#"
    echo "# To modify environment variables, edit the source files above."
    echo ""
    echo "# ============================================"
    echo "# From .pcs.env (system configuration)"
    echo "# ============================================"
    cat "$PCS_ENV_FILE" 2>/dev/null || true
    echo ""
    echo "# ============================================"
    echo "# From .pcs.secret.env (secrets)"
    echo "# ============================================"
    cat "$SECRET_ENV_FILE" 2>/dev/null || true
    echo ""
    echo "# ============================================"
    echo "# From .ynd.user.env (user data)"
    echo "# ============================================"
    cat "$USER_ENV_FILE" 2>/dev/null || true
} > "$OUTPUT_ENV_FILE"

echo "All required environment variables are valid"
echo "Generated combined .env file at $OUTPUT_ENV_FILE"
