#!/bin/bash
# Validate required environment variables and generate combined .env file

set -e

COMPOSE_DIR=/DATA/AppData/casaos/apps/yundera
PCS_ENV_FILE="$COMPOSE_DIR/.pcs.env"
SECRET_ENV_FILE="$COMPOSE_DIR/.pcs.secret.env"
USER_ENV_FILE="$COMPOSE_DIR/.ynd.user.env"
OUTPUT_ENV_FILE="$COMPOSE_DIR/.env"

# Sanitize env file: squeeze consecutive blank lines and ensure trailing newline
# This cleans up any accumulated empty lines from previous script versions
sanitize_env_file() {
    local file="$1"
    if [ -f "$file" ]; then
        cat -s "$file" > "$file.tmp" && mv "$file.tmp" "$file"
        sed -i -e '$a\' "$file" 2>/dev/null || true
    fi
}

# Sanitize all env files before processing
sanitize_env_file "$PCS_ENV_FILE"
sanitize_env_file "$SECRET_ENV_FILE"
sanitize_env_file "$USER_ENV_FILE"

# Define required environment variables
REQUIRED_VARS=("DOMAIN" "PROVIDER_STR" "UID")

# Declare associative array to store environment variables
declare -A env_vars

# Function to read environment file and store variables
read_env_file() {
    local file="$1"
    if [ -f "$file" ]; then
        while IFS='=' read -r key value || [ -n "$key" ]; do
            # Skip comments and empty lines
            [[ $key =~ ^#.*$ || -z $key ]] && continue

            # Remove any surrounding quotes from the value
            value=$(echo "$value" | sed -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'$//")

            # Store the key-value pair
            env_vars["$key"]="$value"

        done < "$file"
    else
        echo "Warning: Environment file not found: $file" >&2
    fi
}

# Read all three environment files
read_env_file "$PCS_ENV_FILE"
read_env_file "$SECRET_ENV_FILE"
read_env_file "$USER_ENV_FILE"

# Check if all required variables are set and not empty
missing_vars=()
for var in "${REQUIRED_VARS[@]}"; do
    if [[ -z "${env_vars[$var]}" ]]; then
        missing_vars+=("$var")
    fi
done

# Throw error if any required variables are missing
if [[ ${#missing_vars[@]} -gt 0 ]]; then
    echo "Error: The following required environment variables are not set or are empty:" >&2
    printf "  - %s\n" "${missing_vars[@]}" >&2
    echo "Please set these variables in $PCS_ENV_FILE, $SECRET_ENV_FILE, or $USER_ENV_FILE" >&2
    exit 1
fi

# Generate combined .env file for Docker Compose
{
    echo "# AUTO-GENERATED FILE - DO NOT EDIT"
    echo "# This file is automatically generated from:"
    echo "#   - .pcs.env"
    echo "#   - .pcs.secret.env"
    echo "#   - .ynd.user.env"
    echo "# Any changes will be overwritten on next system update."
    echo "#"
    echo "# To modify environment variables, edit the source files above."
    echo ""
    echo "# ============================================"
    echo "# From .pcs.env (system configuration)"
    echo "# ============================================"
    cat "$PCS_ENV_FILE" 2>/dev/null || true
    echo ""
    echo "# ============================================"
    echo "# From .pcs.secret.env (secrets)"
    echo "# ============================================"
    cat "$SECRET_ENV_FILE" 2>/dev/null || true
    echo ""
    echo "# ============================================"
    echo "# From .ynd.user.env (user data)"
    echo "# ============================================"
    cat "$USER_ENV_FILE" 2>/dev/null || true
} > "$OUTPUT_ENV_FILE"

echo "All required environment variables are valid"
echo "Generated combined .env file at $OUTPUT_ENV_FILE"
