#!/bin/bash
set -euo pipefail

# Migration: Ensure .env files exist for all CasaOS apps
# Type: Always-run migration (runs on every template sync)
# Purpose: Generate .env files for apps that are missing them or have outdated format
#
# This migration ensures all CasaOS apps have properly formatted .env files
# with the required environment variables. It runs on every sync to catch
# newly installed apps that may not have gone through the standard flow.
#
# .env files are stored in /DATA/AppData/{app_name}/.env (user data folder)
# NOT in /DATA/AppData/casaos/apps/{app_name}/ (app definition folder)
# This ensures .env files are included in user data backups.

APPS_DIR="/DATA/AppData/casaos/apps"
APPDATA_DIR="/DATA/AppData"
ENV_VERSION="1"

# Skip if apps directory doesn't exist
if [ ! -d "$APPS_DIR" ]; then
    echo "Apps directory does not exist, skipping"
    exit 0
fi

# Get environment variables with defaults
DATA_ROOT="${DATA_ROOT:-/DATA}"
REF_DOMAIN="${REF_DOMAIN:-localhost}"
REF_SCHEME="${REF_SCHEME:-http}"
REF_PORT="${REF_PORT:-80}"
REF_NET="${REF_NET:-pcs}"
PUID="${PUID:-1000}"
PGID="${PGID:-1000}"

# Detect timezone
if [ -f /etc/timezone ]; then
    TZ=$(cat /etc/timezone 2>/dev/null || echo "UTC")
elif [ -L /etc/localtime ]; then
    TZ=$(readlink /etc/localtime | sed 's|.*/zoneinfo/||')
else
    TZ="UTC"
fi

# Track stats
generated_count=0
skipped_count=0

for app_dir in "$APPS_DIR"/*/; do
    # Skip if not a directory
    [ -d "$app_dir" ] || continue

    app_name=$(basename "$app_dir")
    compose_file="$app_dir/docker-compose.yml"

    # .env goes in AppData folder (user data), not apps folder (app definition)
    app_data_dir="$APPDATA_DIR/$app_name"
    env_file="$app_data_dir/.env"

    # Also check old location for migration purposes
    old_env_file="$app_dir/.env"

    # Skip non-compose apps (e.g., yundera settings folder)
    if [ ! -f "$compose_file" ]; then
        continue
    fi

    # Skip if already has .env with current version marker in new location
    if [ -f "$env_file" ] && grep -q "^_CASAOS_ENV_VERSION=$ENV_VERSION" "$env_file" 2>/dev/null; then
        skipped_count=$((skipped_count + 1))
        continue
    fi

    echo "Generating .env for: $app_name"

    # Generate random AUTH_HASH (128 lowercase alphanumeric characters)
    # Check both new and old locations for existing AUTH_HASH to preserve it
    AUTH_HASH=""
    if [ -f "$env_file" ] && grep -q "^AUTH_HASH=" "$env_file" 2>/dev/null; then
        AUTH_HASH=$(grep "^AUTH_HASH=" "$env_file" | cut -d'=' -f2-)
    elif [ -f "$old_env_file" ] && grep -q "^AUTH_HASH=" "$old_env_file" 2>/dev/null; then
        AUTH_HASH=$(grep "^AUTH_HASH=" "$old_env_file" | cut -d'=' -f2-)
    fi

    # Generate new AUTH_HASH if not found
    if [ -z "$AUTH_HASH" ]; then
        # Use head -c to avoid SIGPIPE issues with pipefail
        AUTH_HASH=$(head -c 512 /dev/urandom | tr -dc 'a-z0-9' | head -c 128)
    fi

    # Create app data directory if it doesn't exist
    mkdir -p "$app_data_dir"

    # Write .env file
    cat > "$env_file" << EOF
# CasaOS App Environment File
# Generated by template migration system
# Do not edit manually - regenerated on template sync

_CASAOS_ENV_VERSION=$ENV_VERSION
name=$app_name
domain=$REF_DOMAIN
scheme=$REF_SCHEME
port=$REF_PORT
DATA_ROOT=$DATA_ROOT
REF_DOMAIN=$REF_DOMAIN
REF_SCHEME=$REF_SCHEME
REF_PORT=$REF_PORT
REF_NET=$REF_NET
PUID=$PUID
PGID=$PGID
TZ=$TZ
DefaultUserName=admin
DefaultPassword=casaos
AUTH_HASH=$AUTH_HASH
EOF

    # Set proper ownership (user data should be owned by the app user)
    chown "$PUID:$PGID" "$env_file"
    chmod 644 "$env_file"

    generated_count=$((generated_count + 1))
done

if [ "$generated_count" -gt 0 ] || [ "$skipped_count" -gt 0 ]; then
    echo "Env files: $generated_count generated, $skipped_count already up-to-date"
fi

exit 0
